Counter PR
rojikumari/Assignment-NFX pull request #1
Opened 2022-01-04 10:12 UTC by rojikumari

made counter using react hook.

2022-01-04 11:32 UTC, kumarparth380 requested changes
1. Redux implementation of counter is missing
2. Login page logic doesn't make any sense as of now. Refactor it to use the normalize state data and use formik.

2022-01-04 11:32 UTC, kumarparth380 commented on src/pages/public/counter/index.js
> +        <Button sx={{ ml: 3 , fontSize : 17, fontWeight: 'Bol',padding : 2}} variant="contained" onClick={() => setData(data + 1)}>
avoid using inline styles

2022-01-05 09:45 UTC, rojikumari commented on src/pages/public/counter/index.js
> +        <Button sx={{ ml: 3 , fontSize : 17, fontWeight: 'Bol',padding : 2}} variant="contained" onClick={() => setData(data + 1)}>
resolved inline styles

2022-01-05 12:53 UTC, kumarparth380 approved these changes

2022-01-06 06:43 UTC, merged